version: "3"

services:
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
	    - ./balancer.conf:/usr/local/apache2/conf/balancer.conf
      - /ssl-certbot:/usr/local/apache2/ssl
    restart: always